[package]
name = "rust"
version = "0.1.0"
edition = "2021"
default-run = "rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.3"

[[bin]]
name = "new"
path = "src/new.rs"