name: test

on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - 'Cargo.*'
      - '.github/workflows/rust-**'
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.*'
      - '.github/workflows/rust-**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        working-directory: ./rust
        run: cargo test
      - name: Check
        working-directory: ./rust
        run: cargo check